  1 [functions]
   2   # Устанавливает тайм-аут для всех функций в секундах.
   3   # Максимальное значение зависит от вашего тарифного плана Netlify.
   4   # Попробуйте установить 26 или 30, если ваш план это позволяет.
   5   timeout = 30
